---
title: "Phenotype Stats Analysis"
author: "Carmen Emborski"
date: "5/11/2018"
output: html_document
---
Programs and Data:
```{r setup, include=FALSE}
library(ggplot2)
library(gridExtra)
library(reshape2)
library(multcomp)
library(boot)
library(lsmeans)
library(ggsignif)
library(grid)
library(gtable)
library(RCurl)
library(dplyr)
library(tidyr)
library(plyr)
library(broom)

#import data
dat <- read.csv("https://raw.githubusercontent.com/cemborski/Horizontal-transmission-of-altered-phenotypes/master/Phenotype%20Analysis/phenotype_data")
```
Run Contrasts:
```{r cars}
####TAG ####
dat$Antibiotic <- factor(dat$Antibiotic, levels = c("antibiotic", "no antibiotic"))
dat$Generation <- factor(dat$Generation, levels = c("F1", "F2", "F3"))

#Model
fat.lm <- glm(TAG ~ GenTreatment*Antibiotic*Generation+Fat.Weight, data=dat)
summary(fat.lm)

#H1
fat.contrast.matrix <- rbind(
  'N.+ vs C.+ (F1)' = c(1,-1,0,0,0,0,0,0,0,0, 0,0,0), 
  'N.- vs C.- (F1)' = c(0,0,1,0,0,0,-1,0,0,0, 0,0,0), 
  'N.+ vs C.+ (F2)' = c(0,0,0,1,0,0,0,-1,0,0, 0,0,0), 
  'N.- vs C.- (F2)' = c(0,0,0,0,0,0,0,0,0,1, 0,-1,0), 
  'N.+ vs C.+ (F3)' = c(0,0,0,0,1,0,0,0,-1,0, 0,0,0), 
  'N.- vs C.- (F3)' = c(0,0,0,0,0,0,0,0,0,0, 1,0,-1)) #All Correct.
fat.comps <- glht(fat.lm, fat.contrast.matrix)
H1.tag <- summary(fat.comps)


#H2 (F1) Test:
dat$Generation <- factor(dat$Generation, levels = c("F3", "F2", "F1"))
F1.fat.lm <- glm(TAG ~ GenTreatment*Antibiotic*Generation+Fat.Weight, data=dat)
#summary(F1.fat.lm)
Kno_antibiotic <- rep(0,length(F1.fat.lm$coefficients))
names(Kno_antibiotic) <- names(F1.fat.lm$coefficients)
Kantibiotic <- rep(0,length(F1.fat.lm $coefficients))
names(Kantibiotic) <- names(F1.fat.lm $coefficients)
Kantibiotic["GenerationF1"] <- 1 
Kantibiotic["GenTreatmentN:GenerationF1"] <- -1 
Kno_antibiotic["Antibioticno antibiotic:GenerationF1"] <- 1 
Kno_antibiotic["GenTreatmentN:Antibioticno antibiotic:GenerationF1"] <- -1 
Ka <- matrix(Kno_antibiotic,1) - matrix(Kantibiotic,1)
H2F1.tag <- summary(glht(F1.fat.lm, linfct = Ka))
H2F1.tag
#Is the effect smaller in antibiotics? #Yes. 
abs(F1.fat.lm$coefficients["Antibioticno antibiotic"] -
        fat.lm$coefficients["GenTreatmentN:Antibioticno antibiotic"]) > 
abs(F1.fat.lm$coefficients["(Intercept)"] -
      fat.lm$coefficients["GenTreatmentN"]) 

#H2 (F2) Test:
Kno_antibiotic <- rep(0,length(fat.lm$coefficients))
names(Kno_antibiotic) <- names(fat.lm$coefficients)
Kantibiotic <- rep(0,length(fat.lm $coefficients))
names(Kantibiotic) <- names(fat.lm $coefficients)
Kantibiotic["GenTreatmentN:GenerationF2"] <- 1 
Kantibiotic["GenerationF2"] <- -1 
Kno_antibiotic["GenTreatmentN:Antibioticno antibiotic:GenerationF2"] <- 1 
Kno_antibiotic["Antibioticno antibiotic:GenerationF2"] <- -1 
Ka <- matrix(Kno_antibiotic,1) - matrix(Kantibiotic,1)
H2F2.tag <-summary(glht(fat.lm, linfct = Ka))
H2F2.tag
#Is the effect smaller in antibiotics?
abs(fat.lm$coefficients["Antibioticno antibiotic:GenerationF2"] -
        fat.lm$coefficients["GenTreatmentN:Antibioticno antibiotic:GenerationF2"]) >
abs(fat.lm$coefficients["GenerationF2"] -
      fat.lm$coefficients["GenTreatmentN:GenerationF2"])  

#H2 (F3) Test:
Kno_antibiotic <- rep(0,length(fat.lm$coefficients))
names(Kno_antibiotic) <- names(fat.lm$coefficients)
Kantibiotic <- rep(0,length(fat.lm $coefficients))
names(Kantibiotic) <- names(fat.lm $coefficients)
Kantibiotic["GenTreatmentN:GenerationF3"] <- 1 
Kantibiotic["GenerationF3"] <- -1 
Kno_antibiotic["GenTreatmentN:Antibioticno antibiotic:GenerationF3"] <- 1 
Kno_antibiotic["Antibioticno antibiotic:GenerationF3"] <- -1 
Ka <- matrix(Kno_antibiotic,1) - matrix(Kantibiotic,1)
H2F3.tag <-summary(glht(fat.lm, linfct = Ka))
H2F3.tag
#Is the effect smaller in antibiotics?
abs(fat.lm$coefficients["Antibioticno antibiotic:GenerationF3"] -
        fat.lm$coefficients["GenTreatmentN:Antibioticno antibiotic:GenerationF3"]) >
abs(fat.lm$coefficients["GenerationF3"] -
      fat.lm$coefficients["GenTreatmentN:GenerationF3"])



#### Glycogen ####
dat$Antibiotic <- factor(dat$Antibiotic, levels = c("antibiotic", "no antibiotic"))
dat$Generation <- factor(dat$Generation, levels = c("F1", "F2", "F3"))

#Model
glyc.lm <- glm(Glycogen ~ GenTreatment*Antibiotic*Generation+Sugar.Weight, data=dat)
summary(glyc.lm)

#H1
glyc.contrast.matrix <- rbind(
  'N.+ vs C.+ (F1)' = c(1,-1,0,0,0,0,0,0,0,0, 0,0,0), 
  'N.- vs C.- (F1)' = c(0,0,1,0,0,0,-1,0,0,0, 0,0,0), 
  'N.+ vs C.+ (F2)' = c(0,0,0,1,0,0,0,-1,0,0, 0,0,0), 
  'N.- vs C.- (F2)' = c(0,0,0,0,0,0,0,0,0,1, 0,-1,0), 
  'N.+ vs C.+ (F3)' = c(0,0,0,0,1,0,0,0,-1,0, 0,0,0), 
  'N.- vs C.- (F3)' = c(0,0,0,0,0,0,0,0,0,0, 1,0,-1)) #All Correct.
glyc.comps <- glht(glyc.lm, glyc.contrast.matrix)
H1.glyc <- summary(glyc.comps)

#H2 (F1) Test:
Kno_antibiotic <- rep(0,length(glyc.lm$coefficients))
names(Kno_antibiotic) <- names(glyc.lm$coefficients)
Kantibiotic <- rep(0,length(glyc.lm $coefficients))
names(Kantibiotic) <- names(glyc.lm $coefficients)
Kantibiotic["(Intercept)"] <- 1 
Kantibiotic["GenTreatmentN"] <- -1 
Kno_antibiotic["Antibioticno antibiotic"] <- 1 
Kno_antibiotic["GenTreatmentN:Antibioticno antibiotic"] <- -1 
Ka <- matrix(Kno_antibiotic,1) - matrix(Kantibiotic,1)
H2F1.glyc <- summary(glht(glyc.lm, linfct = Ka))
H2F1.glyc
#Is the effect smaller in antibiotics? #Yes. 
abs(glyc.lm$coefficients["Antibioticno antibiotic"] -
        glyc.lm$coefficients["GenTreatmentN:Antibioticno antibiotic"]) > 
abs(glyc.lm$coefficients["(Intercept)"] -
      glyc.lm$coefficients["GenTreatmentN"]) 

#H2 (F2) Test:
Kno_antibiotic <- rep(0,length(glyc.lm$coefficients))
names(Kno_antibiotic) <- names(glyc.lm$coefficients)
Kantibiotic <- rep(0,length(glyc.lm $coefficients))
names(Kantibiotic) <- names(glyc.lm $coefficients)
Kantibiotic["GenTreatmentN:GenerationF2"] <- 1 
Kantibiotic["GenerationF2"] <- -1 
Kno_antibiotic["GenTreatmentN:Antibioticno antibiotic:GenerationF2"] <- 1 
Kno_antibiotic["Antibioticno antibiotic:GenerationF2"] <- -1 
Ka <- matrix(Kno_antibiotic,1) - matrix(Kantibiotic,1)
H2F2.glyc <-summary(glht(glyc.lm, linfct = Ka))
H2F2.glyc
#Is the effect smaller in antibiotics?
abs(glyc.lm$coefficients["Antibioticno antibiotic:GenerationF2"] -
        glyc.lm$coefficients["GenTreatmentN:Antibioticno antibiotic:GenerationF2"]) >
abs(glyc.lm$coefficients["GenerationF2"] -
      glyc.lm$coefficients["GenTreatmentN:GenerationF2"])  

#H2 (F3) Test:
Kno_antibiotic <- rep(0,length(glyc.lm$coefficients))
names(Kno_antibiotic) <- names(glyc.lm$coefficients)
Kantibiotic <- rep(0,length(glyc.lm $coefficients))
names(Kantibiotic) <- names(glyc.lm $coefficients)
Kantibiotic["GenTreatmentN:GenerationF3"] <- 1 
Kantibiotic["GenerationF3"] <- -1 
Kno_antibiotic["GenTreatmentN:Antibioticno antibiotic:GenerationF3"] <- 1 
Kno_antibiotic["Antibioticno antibiotic:GenerationF3"] <- -1 
Ka <- matrix(Kno_antibiotic,1) - matrix(Kantibiotic,1)
H2F3.glyc <-summary(glht(glyc.lm, linfct = Ka))
H2F3.glyc
#Is the effect smaller in antibiotics?
abs(glyc.lm$coefficients["Antibioticno antibiotic:GenerationF3"] -
        glyc.lm$coefficients["GenTreatmentN:Antibioticno antibiotic:GenerationF3"]) >
abs(glyc.lm$coefficients["GenerationF3"] -
      glyc.lm$coefficients["GenTreatmentN:GenerationF3"])



#### Trehalose ####
dat$Antibiotic <- factor(dat$Antibiotic, levels = c("antibiotic", "no antibiotic"))

#Model
treh.lm <- glm(Trehalose ~ GenTreatment*Antibiotic*Generation+Sugar.Weight, data=dat)
summary(treh.lm)

#H1
treh.contrast.matrix <- rbind(
  'N.+ vs C.+ (F1)' = c(1,-1,0,0,0,0,0,0,0,0, 0,0,0), 
  'N.- vs C.- (F1)' = c(0,0,1,0,0,0,-1,0,0,0, 0,0,0), 
  'N.+ vs C.+ (F2)' = c(0,0,0,1,0,0,0,-1,0,0, 0,0,0), 
  'N.- vs C.- (F2)' = c(0,0,0,0,0,0,0,0,0,1, 0,-1,0), 
  'N.+ vs C.+ (F3)' = c(0,0,0,0,1,0,0,0,-1,0, 0,0,0), 
  'N.- vs C.- (F3)' = c(0,0,0,0,0,0,0,0,0,0, 1,0,-1)) #All Correct.
treh.comps <- glht(treh.lm, treh.contrast.matrix)
H1.treh <- summary(treh.comps)

#H2 (F1) Test:
Kno_antibiotic <- rep(0,length(treh.lm$coefficients))
names(Kno_antibiotic) <- names(treh.lm$coefficients)
Kantibiotic <- rep(0,length(treh.lm $coefficients))
names(Kantibiotic) <- names(treh.lm $coefficients)
Kantibiotic["(Intercept)"] <- 1 
Kantibiotic["GenTreatmentN"] <- -1 
Kno_antibiotic["Antibioticno antibiotic"] <- 1 
Kno_antibiotic["GenTreatmentN:Antibioticno antibiotic"] <- -1 
Ka <- matrix(Kno_antibiotic,1) - matrix(Kantibiotic,1)
H2F1.treh <- summary(glht(treh.lm, linfct = Ka))
H2F1.treh
#Is the effect smaller in antibiotics? #Yes. 
abs(treh.lm$coefficients["Antibioticno antibiotic"] -
        treh.lm$coefficients["GenTreatmentN:Antibioticno antibiotic"]) > 
abs(treh.lm$coefficients["(Intercept)"] -
      treh.lm$coefficients["GenTreatmentN"]) 

#H2 (F2) Test:
Kno_antibiotic <- rep(0,length(treh.lm$coefficients))
names(Kno_antibiotic) <- names(treh.lm$coefficients)
Kantibiotic <- rep(0,length(treh.lm $coefficients))
names(Kantibiotic) <- names(treh.lm $coefficients)
Kantibiotic["GenTreatmentN:GenerationF2"] <- 1 
Kantibiotic["GenerationF2"] <- -1 
Kno_antibiotic["GenTreatmentN:Antibioticno antibiotic:GenerationF2"] <- 1 
Kno_antibiotic["Antibioticno antibiotic:GenerationF2"] <- -1 
Ka <- matrix(Kno_antibiotic,1) - matrix(Kantibiotic,1)
H2F2.treh <-summary(glht(treh.lm, linfct = Ka))
H2F2.treh
#Is the effect smaller in antibiotics?
abs(treh.lm$coefficients["Antibioticno antibiotic:GenerationF2"] -
        treh.lm$coefficients["GenTreatmentN:Antibioticno antibiotic:GenerationF2"]) >
abs(treh.lm$coefficients["GenerationF2"] -
      treh.lm$coefficients["GenTreatmentN:GenerationF2"])  

#H2 (F3) Test:
Kno_antibiotic <- rep(0,length(treh.lm$coefficients))
names(Kno_antibiotic) <- names(treh.lm$coefficients)
Kantibiotic <- rep(0,length(treh.lm $coefficients))
names(Kantibiotic) <- names(treh.lm $coefficients)
Kantibiotic["GenTreatmentN:GenerationF3"] <- 1 
Kantibiotic["GenerationF3"] <- -1 
Kno_antibiotic["GenTreatmentN:Antibioticno antibiotic:GenerationF3"] <- 1 
Kno_antibiotic["Antibioticno antibiotic:GenerationF3"] <- -1 
Ka <- matrix(Kno_antibiotic,1) - matrix(Kantibiotic,1)
H2F3.treh <-summary(glht(treh.lm, linfct = Ka))
H2F3.treh
#Is the effect smaller in antibiotics?
abs(treh.lm$coefficients["Antibioticno antibiotic:GenerationF3"] -
        treh.lm$coefficients["GenTreatmentN:Antibioticno antibiotic:GenerationF3"]) > abs(treh.lm$coefficients["GenerationF3"] -
      treh.lm$coefficients["GenTreatmentN:GenerationF3"])



#### Glucose ####
dat$Antibiotic <- factor(dat$Antibiotic, levels = c("antibiotic", "no antibiotic"))

#Model
gluc.lm <- glm(Glucose ~ GenTreatment*Antibiotic*Generation+Sugar.Weight, data=dat)
summary(gluc.lm)

#H1
gluc.contrast.matrix <- rbind(
  'N.+ vs C.+ (F1)' = c(1,-1,0,0,0,0,0,0,0,0, 0,0,0), 
  'N.- vs C.- (F1)' = c(0,0,1,0,0,0,-1,0,0,0, 0,0,0), 
  'N.+ vs C.+ (F2)' = c(0,0,0,1,0,0,0,-1,0,0, 0,0,0), 
  'N.- vs C.- (F2)' = c(0,0,0,0,0,0,0,0,0,1, 0,-1,0), 
  'N.+ vs C.+ (F3)' = c(0,0,0,0,1,0,0,0,-1,0, 0,0,0), 
  'N.- vs C.- (F3)' = c(0,0,0,0,0,0,0,0,0,0, 1,0,-1)) #All Correct.
gluc.comps <- glht(gluc.lm, gluc.contrast.matrix)
H1.gluc <- summary(gluc.comps)

#H2 (F1) Test:
Kno_antibiotic <- rep(0,length(gluc.lm$coefficients))
names(Kno_antibiotic) <- names(gluc.lm$coefficients)
Kantibiotic <- rep(0,length(gluc.lm $coefficients))
names(Kantibiotic) <- names(gluc.lm $coefficients)
Kantibiotic["(Intercept)"] <- 1 
Kantibiotic["GenTreatmentN"] <- -1 
Kno_antibiotic["Antibioticno antibiotic"] <- 1 
Kno_antibiotic["GenTreatmentN:Antibioticno antibiotic"] <- -1 
Ka <- matrix(Kno_antibiotic,1) - matrix(Kantibiotic,1)
H2F1.gluc <- summary(glht(gluc.lm, linfct = Ka))
H2F1.gluc
#Is the effect smaller in antibiotics? #Yes. 
abs(gluc.lm$coefficients["Antibioticno antibiotic"] -
        gluc.lm$coefficients["GenTreatmentN:Antibioticno antibiotic"]) > 
abs(gluc.lm$coefficients["(Intercept)"] -
      gluc.lm$coefficients["GenTreatmentN"]) 

#H2 (F2) Test:
Kno_antibiotic <- rep(0,length(gluc.lm$coefficients))
names(Kno_antibiotic) <- names(gluc.lm$coefficients)
Kantibiotic <- rep(0,length(gluc.lm $coefficients))
names(Kantibiotic) <- names(gluc.lm $coefficients)
Kantibiotic["GenTreatmentN:GenerationF2"] <- 1 
Kantibiotic["GenerationF2"] <- -1 
Kno_antibiotic["GenTreatmentN:Antibioticno antibiotic:GenerationF2"] <- 1 
Kno_antibiotic["Antibioticno antibiotic:GenerationF2"] <- -1 
Ka <- matrix(Kno_antibiotic,1) - matrix(Kantibiotic,1)
H2F2.NF.Ta <-summary(glht(gluc.lm, linfct = Ka))
H2F2.NF.Ta
#Is the effect smaller in antibiotics?
abs(gluc.lm$coefficients["Antibioticno antibiotic:GenerationF2"] -
        gluc.lm$coefficients["GenTreatmentN:Antibioticno antibiotic:GenerationF2"]) >
abs(gluc.lm$coefficients["GenerationF2"] -
      gluc.lm$coefficients["GenTreatmentN:GenerationF2"])  

#H2 (F3) Test:
Kno_antibiotic <- rep(0,length(gluc.lm$coefficients))
names(Kno_antibiotic) <- names(gluc.lm$coefficients)
Kantibiotic <- rep(0,length(gluc.lm $coefficients))
names(Kantibiotic) <- names(gluc.lm $coefficients)
Kantibiotic["GenTreatmentN:GenerationF3"] <- 1 
Kantibiotic["GenerationF3"] <- -1 
Kno_antibiotic["GenTreatmentN:Antibioticno antibiotic:GenerationF3"] <- 1 
Kno_antibiotic["Antibioticno antibiotic:GenerationF3"] <- -1 
Ka <- matrix(Kno_antibiotic,1) - matrix(Kantibiotic,1)
H2F3.NF.Ta <-summary(glht(gluc.lm, linfct = Ka))
H2F3.NF.Ta
#Is the effect smaller in antibiotics?
abs(gluc.lm$coefficients["Antibioticno antibiotic:GenerationF3"] -
        gluc.lm$coefficients["GenTreatmentN:Antibioticno antibiotic:GenerationF3"]) >
abs(gluc.lm$coefficients["GenerationF3"] -
      gluc.lm$coefficients["GenTreatmentN:GenerationF3"])
```
Make results tables w/ Experiment Wide FDR Corrections:
```{r pressure, echo=FALSE}
H1.results.df <- rbind(tidy(H1.tag) %>% 
                    mutate(metabolite = "TAG") %>% mutate(sex = "female") %>% mutate(treatment = "N") %>% 
                    mutate(antibiotic = ifelse(grepl("- ", lhs), "no antibiotic", "antibiotic")) %>% 
                    mutate(generation = ifelse(grepl("F1", lhs), "F1", ifelse(grepl("F2", lhs), "F2", "F3"))),
                tidy(H1.glyc) %>% 
                    mutate(metabolite = "Glycogen") %>% mutate(sex = "female") %>% mutate(treatment = "N") %>% 
                    mutate(antibiotic = ifelse(grepl("- ", lhs), "no antibiotic", "antibiotic")) %>% 
                    mutate(generation = ifelse(grepl("F1", lhs), "F1", ifelse(grepl("F2", lhs), "F2", "F3"))),
                tidy(H1.treh) %>% 
                    mutate(metabolite = "Trehalose") %>% mutate(sex = "female") %>% mutate(treatment = "N") %>% 
                    mutate(antibiotic = ifelse(grepl("- ", lhs), "no antibiotic", "antibiotic")) %>% 
                    mutate(generation = ifelse(grepl("F1", lhs), "F1", ifelse(grepl("F2", lhs), "F2", "F3"))),
                tidy(H1.gluc) %>% 
                    mutate(metabolite = "Glucose") %>% mutate(sex = "female") %>% mutate(treatment = "N") %>% 
                    mutate(antibiotic = ifelse(grepl("- ", lhs), "no antibiotic", "antibiotic")) %>% 
                    mutate(generation = ifelse(grepl("F1", lhs), "F1", ifelse(grepl("F2", lhs), "F2", "F3"))))
H1.results.df <- H1.results.df %>% mutate(pAdj = p.adjust(p.value, method = "fdr")) 
H1.results.df <- H1.results.df %>% mutate(significance = symnum(pAdj, corr = FALSE, na = FALSE, cutpoints = c(0, 0.001, 0.01, 0.05, 0.1, 1), symbols = c("***", "**", "*", ".", " ")))
H1.results.df <- H1.results.df[,-2]
colnames(H1.results.df)[1] <- "comparison" 
H1.results.df <- H1.results.df[c("metabolite", "comparison", "treatment", "antibiotic", "sex", "generation", "estimate", "std.error", "statistic", "p.value", "pAdj", "significance")]
write.csv(H1.results.df, file = "New N (NC fem only) SuppTable 1.csv")


H2.results.df <- rbind(tidy(H2F1.tag) %>% mutate(comparison = "F1 TAG Female (N-)-(C-) vs. (N+)-(C+)") %>%
                      mutate(metabolite = "TAG") %>% mutate(sex = "female") %>% 
                      mutate(treatment = "N") %>% mutate(generation = "F1"),
                 tidy(H2F2.tag) %>% mutate(comparison = "F2 TAG Female (N-)-(C-) vs. (N+)-(C+)") %>%
                      mutate(metabolite = "TAG") %>% mutate(sex = "female") %>% 
                      mutate(treatment = "N") %>% mutate(generation = "F2"),
                 tidy(H2F3.tag) %>% mutate(comparison = "F3 TAG Female (N-)-(C-) vs. (N+)-(C+)") %>%
                      mutate(metabolite = "TAG") %>% mutate(sex = "female") %>% 
                      mutate(treatment = "N") %>% mutate(generation = "F3"),
                 tidy(H2F1.glyc) %>% mutate(comparison = "F1 Glycogen Female (N-)-(C-) vs. (N+)-(C+)") %>%
                      mutate(metabolite = "Glycogen") %>% mutate(sex = "female") %>% 
                      mutate(treatment = "N") %>% mutate(generation = "F1"),
                 tidy(H2F2.glyc) %>% mutate(comparison = "F2 Glycogen Female (N-)-(C-) vs. (N+)-(C+)") %>%
                      mutate(metabolite = "Glycogen") %>% mutate(sex = "female") %>% 
                      mutate(treatment = "N") %>% mutate(generation = "F2"),
                 tidy(H2F3.glyc) %>% mutate(comparison = "F3 Glycogen Female (N-)-(C-) vs. (N+)-(C+)") %>%
                      mutate(metabolite = "Glycogen") %>% mutate(sex = "female") %>% 
                      mutate(treatment = "N") %>% mutate(generation = "F3"),
                 tidy(H2F1.treh) %>% mutate(comparison = "F1 Trehalose Female (N-)-(C-) vs. (N+)-(C+)") %>%
                      mutate(metabolite = "Trehalose") %>% mutate(sex = "female") %>% 
                      mutate(treatment = "N") %>% mutate(generation = "F1"),
                 tidy(H2F2.treh) %>% mutate(comparison = "F2 Trehalose Female (N-)-(C-) vs. (N+)-(C+)") %>%
                      mutate(metabolite = "Trehalose") %>% mutate(sex = "female") %>% 
                      mutate(treatment = "N") %>% mutate(generation = "F2"),
                 tidy(H2F3.treh) %>% mutate(comparison = "F3 Trehalose Female (N-)-(C-) vs. (N+)-(C+)") %>%
                      mutate(metabolite = "Trehalose") %>% mutate(sex = "female") %>% 
                      mutate(treatment = "N") %>% mutate(generation = "F3"),
                 tidy(H2F1.glyc) %>% mutate(comparison = "F1 Glucose Female (N-)-(C-) vs. (N+)-(C+)") %>%
                      mutate(metabolite = "Glucose") %>% mutate(sex = "female") %>% 
                      mutate(treatment = "N") %>% mutate(generation = "F1"),
                 tidy(H2F2.glyc) %>% mutate(comparison = "F2 Glucose Female (N-)-(C-) vs. (N+)-(C+)") %>%
                      mutate(metabolite = "Glucose") %>% mutate(sex = "female") %>% 
                      mutate(treatment = "N") %>% mutate(generation = "F2"),
                 tidy(H2F3.glyc) %>% mutate(comparison = "F3 Glucose Female (N-)-(C-) vs. (N+)-(C+)") %>%
                      mutate(metabolite = "Glucose") %>% mutate(sex = "female") %>% 
                      mutate(treatment = "N") %>% mutate(generation = "F3"))
H2.results.df <- H2.results.df %>% mutate(pAdj = p.adjust(p.value, method = "fdr")) 
H2.results.df <- H2.results.df %>% mutate(significance = symnum(pAdj, corr = FALSE, na = FALSE, cutpoints = c(0, 0.001, 0.01, 0.05, 0.1, 1), symbols = c("***", "**", "*", ".", " ")))
H2.results.df <- H2.results.df[c("metabolite", "comparison", "treatment", "sex", "generation", "estimate", "std.error", "statistic", "p.value", "pAdj", "significance")]
write.csv(H2.results.df, file = "New N (NC fem only) SuppTable 2.csv")        
```
Create plot data frame:
```{r}
##Triglycerides:
fat <- dat[,-c(8,9,10,11)]
colnames(fat)[8] <- "weight"

#TAG
TaW <- data.frame(Generation=character, diet=character(),antibiotic=character(), sex=character(), TAG=numeric())
for(i in unique(fat$Generation))
  for(j in unique(fat$GenTreatment))
    for(k in unique(fat$Antibiotic))
      for(l in unique(fat$Sex)){
        temp <- subset(fat, Generation == i & GenTreatment == j & Antibiotic == k & Sex == l)
        temp$TagWt <- ((subset(fat, Generation == i & GenTreatment == j & Antibiotic == k & Sex ==l)$TAG)/(subset(fat, Generation == i & GenTreatment == j & Antibiotic == k & Sex == l)$weight))
        TaW <- rbind(TaW, temp)}


#Data Subset for Sugar Plots:
sugar <- dat[,-c(12,13)]
colnames(sugar)[8] <- "weight"

#Glucose
GW <- data.frame(Generation=character, diet=character(),antibiotic=character() , sex=character(), Glucose=numeric())
for(i in unique(sugar$Generation))
  for(j in unique(sugar$GenTreatment))
    for(k in unique(sugar$Antibiotic))
      for(l in unique(sugar$Sex)){
        temp <- subset(sugar, Generation == i & GenTreatment == j & Antibiotic == k & Sex == l)
        temp$GlucoseWt <- ((subset(sugar, Generation == i & GenTreatment == j & Antibiotic == k & Sex ==l)$Glucose)/(subset(sugar, Generation == i & GenTreatment == j & Antibiotic == k & Sex == l)$weight))
        GW <- rbind(GW, temp)}

#Trehalose
TW <- data.frame(Generation=character, diet=character(),antibiotic=character() , sex=character(), Trehalose=numeric())
for(i in unique(sugar$Generation))
  for(j in unique(sugar$GenTreatment))
    for(k in unique(sugar$Antibiotic))
      for(l in unique(sugar$Sex)){
        temp <- subset(sugar, Generation == i & GenTreatment == j & Antibiotic == k & Sex == l)
        temp$TrehaloseWt <- ((subset(sugar, Generation == i & GenTreatment == j & Antibiotic == k & Sex ==l)$Trehalose)/(subset(sugar, Generation == i & GenTreatment == j & Antibiotic == k & Sex == l)$weight))
        TW <- rbind(TW, temp)}

#Glycogen
YW <- data.frame(Generation=character, diet=character(),antibiotic=character() , sex=character(), Glycogen=numeric())
for(i in unique(sugar$Generation))
  for(j in unique(sugar$GenTreatment))
    for(k in unique(sugar$Antibiotic))
      for(l in unique(sugar$Sex)){
        temp <- subset(sugar, Generation == i & GenTreatment == j & Antibiotic == k & Sex == l) 
        temp$GlycogenWt <- ((subset(sugar, Generation == i & GenTreatment == j & Antibiotic == k & Sex ==l)$Glycogen)/(subset(sugar, Generation == i & GenTreatment == j & Antibiotic == k & Sex == l)$weight))
        YW <- rbind(YW, temp)} 
```
Plot: Female TAG:
```{r}
#RAW TAG - N, female
RawF1.N.Fem.TAG.p <- ggplot(subset(TaW, Generation=="F1"), aes(Antibiotic, TagWt, fill=GenTreatment)) + scale_fill_manual(values=c("#FF9966", "#33CCFF")) + geom_boxplot(outlier.colour="gray") + theme_bw() + coord_cartesian(ylim = c(0, 22.5)) + ggtitle("F1") + xlab("") + ylab("") + theme(legend.key.size =  unit(1, "in"), legend.text = element_text(size=18), legend.title = element_text(size=18, face="bold"), title=element_text(size=18, face="bold"), axis.title=element_text(size=16), axis.text.x=element_text(size=18, vjust=0.5, face="bold"), axis.text.y=element_text(size=22), plot.title = element_text(size=28, hjust=0.5))
RawF1.N.Fem.TAG.p <- RawF1.N.Fem.TAG.p + geom_signif(annotation="", y_position=16, xmin=0.8, xmax=1.2, tip_length = c(0.015, 0.015), textsize = 12, size=0.75) + geom_signif(annotation="***", y_position=16, xmin=1.80, xmax=2.2, tip_length = c(0.015, 0.015), textsize = 12, size=0.75) + geom_signif(annotation="***", y_position=20.75, xmin=1, xmax=2, tip_length = c(0.055, 0.055), textsize = 12, size=0.75) + geom_segment(aes(x=0.75, xend=1.25, y=19.65, yend=19.65)) + geom_segment(aes(x=1.75, xend=2.25, y=19.65, yend=19.65))
RawF1.N.Fem.TAG.p

RawF2.N.Fem.TAG.p <- ggplot(subset(TaW, Generation=="F2"), aes(Antibiotic, TagWt, fill=GenTreatment)) + scale_fill_manual(values=c("#FF9966", "#33CCFF")) + geom_boxplot(outlier.colour="gray") + theme_bw() + coord_cartesian(ylim = c(0, 22.5)) + ggtitle("F2") + xlab("") + ylab("") + theme(title=element_text(size=18, face="bold"), axis.title=element_text(size=16), axis.text.x=element_text(size=18, vjust=0.5, face="bold"), axis.text.y=element_text(size=22), plot.title = element_text(size=28, hjust=0.5))
RawF2.N.Fem.TAG.p <- RawF2.N.Fem.TAG.p + geom_signif(annotation="", y_position=12.5, xmin=0.8, xmax=1.2, tip_length = c(0.015, 0.015), textsize = 12, size=0.75) + geom_signif(annotation="**", y_position=12.5, xmin=1.80, xmax=2.2, tip_length = c(0.015, 0.015), textsize = 12, size=0.75) + geom_signif(annotation="*", y_position=20.75, xmin=1, xmax=2, tip_length = c(0.055, 0.055), textsize = 12, size=0.75) + geom_segment(aes(x=0.75, xend=1.25, y=19.65, yend=19.65)) + geom_segment(aes(x=1.75, xend=2.25, y=19.65, yend=19.65))
RawF2.N.Fem.TAG.p

RawF3.N.Fem.TAG.p <- ggplot(subset(TaW, Generation=="F3"), aes(Antibiotic, TagWt, fill=GenTreatment)) + scale_fill_manual(values=c("#FF9966", "#33CCFF")) + geom_boxplot(outlier.colour="gray") + theme_bw() + coord_cartesian(ylim = c(0, 22.5)) + ggtitle("F3") + xlab("") + ylab("") + theme(title=element_text(size=18, face="bold"), axis.title=element_text(size=16), axis.text.x=element_text(size=18, vjust=0.5, face="bold"), axis.text.y=element_text(size=22), plot.title = element_text(size=28, hjust=0.5))
RawF3.N.Fem.TAG.p <- RawF3.N.Fem.TAG.p + geom_signif(annotation="", y_position=12.5, xmin=0.8, xmax=1.2, tip_length = c(0.015, 0.015), textsize = 12, size=0.75) + geom_signif(annotation="***", y_position=12.5, xmin=1.80, xmax=2.2, tip_length = c(0.015, 0.015), textsize = 12, size=0.75) + geom_signif(annotation="***", y_position=20.75, xmin=1, xmax=2, tip_length = c(0.055, 0.055), textsize = 12, size=0.75) + geom_segment(aes(x=0.75, xend=1.25, y=19.65, yend=19.65)) + geom_segment(aes(x=1.75, xend=2.25, y=19.65, yend=19.65))
RawF3.N.Fem.TAG.p

g_legend<-function(a.gplot){
  tmp <- ggplot_gtable(ggplot_build(a.gplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)}
mylegend<-g_legend(RawF1.N.Fem.TAG.p)

GenNFTag <- grid.arrange(arrangeGrob(RawF1.N.Fem.TAG.p + theme(legend.position="none"), RawF2.N.Fem.TAG.p + theme(legend.position="none"), RawF3.N.Fem.TAG.p + theme(legend.position="none"), ncol=3, top=textGrob("Triglycerides (Females)", gp = gpar(fontface=2, fontsize=40)), bottom=textGrob("", gp = gpar(fontface=1, fontsize=25)), left=textGrob("Triglycerides/Weight (µg)", rot=90, gp = gpar(fontface=1, fontsize=35))), mylegend, ncol=2, widths=c(10,2))

ggsave("TAG 180513.pdf", GenNFTag, device="pdf", width = 20, height = 7, units = "in")

```
